# vim: syntax=python expandtab
# Simple Snakemake example

configfile: "config/config.yaml"

# Adjust the glob pattern to fit your input file names
SAMPLES = glob_wildcards("input/{sample}_1.fq.gz").sample
print("Found the following samples:")
print(SAMPLES)


rule all:
    input:
        expand("output/convert_to_fasta/{sample}.gchist.txt.gz", sample=SAMPLES),


rule convert_to_fasta:
    """
    Example rule, please modify!
    This uses BBMap's reformat.sh to extract reads from the input files and
    save them as FASTA.
    """
    input:
        read1="input/{sample}_1.fq.gz",
        read2="input/{sample}_2.fq.gz",
    output:
        file1="output/convert_to_fasta/{sample}_1.head.fa.gz",
        file2="output/convert_to_fasta/{sample}_2.head.fa.gz",
        gchist="output/convert_to_fasta/{sample}.gchist.txt",
    log:
        stderr="output/logs/convert_to_fasta/{sample}.stderr",
        stdout="output/logs/convert_to_fasta/{sample}.stdout",
    threads:
        2
    conda:
        "envs/conda.yaml"
    params:
       reads=config["reads_to_extract"],
    shell:
        """
        reformat.sh \
            in1={input.read1} \
            in2={input.read2} \
            out1={output.file1} \
            out2={output.file2} \
            gchist={output.gchist} \
            threads={threads} \
            reads={params.reads} \
            2> {log.stderr} \
            > {log.stdout}
        """


rule compress_gchist:
    """
    Example rule, please modify!
    This uses gzip to compress its input file.
    """
    input:
        gchist=rules.convert_to_fasta.output.gchist,
    output:
        gz="output/convert_to_fasta/{sample}.gchist.txt.gz",
    log:
        stderr="output/logs/compress_gchist/{sample}.stderr",
    threads:
        2
    conda:
        "envs/conda.yaml"
    shell:
        """
        gzip \
            {input.gchist} \
            2> {log.stderr}
        """
